### ISSUE TITLE
Change to use dbt-core-interface instead of vendering

### ISSUE THREAD

**Issue by syou6162** [z3z1ma/dbt-osmosis#108]
- ref: https://github.com/z3z1ma/dbt-osmosis/issues/93

I tried to replace the code under `src/dbt_osmosis/vendored/dbt_core_interface` with https://github.com/z3z1ma/dbt-core-interface. However, there is a subtle difference between these codes, and I expect this difference to grow again in the future, as there are likely to be more recent modifications to the code under vendering.

- https://github.com/z3z1ma/dbt-osmosis/pull/107

In order to continue to make dbt-osmosis a good tool, I think changes are needed to stop vendering and use dbt-core-interface. I will do the following to accomplish this, but would like to hear your thoughts.

- Send several pull requests to delete the differences between `src/dbt_osmosis/vendored/dbt_core_interface` and https://github.com/z3z1ma/dbt-core-interface to the dbt-core- interface repository
- After the difference is eliminated, delete the code in `src/dbt_osmosis/vendored/dbt_core_interface` and switch to importing dbt-core-interface.

If it looks good, I will start with small steps.

**Comment by z3z1ma** [comment]
I agree. The original intent of the `dbt-core-interface` and the fact it even exists as a single file was actually to drive this: https://github.com/AltimateAI/vscode-dbt-power-user/blob/master/dbt_integration.py 

So vendoring it in dbt-osmosis was just proof of concept that anyone can work with dbt api since this file will handle the plumbing. I think its totally fine to simply depend on it and keep changes in one place.

**Comment by syou6162** [comment]
Thank you very much. Now, I will work on sending a pull request to the https://github.com/z3z1ma/dbt-core-interface repository little by little to eliminate the differences!
